#!/usr/bin/env Rscript

#Date April 2017 21
#Read tab delimited file generated by python script on 16s RDP classification
#
# Along with sample name pull columns which have genus of our interest
#
#First column has sample names
#First seven rows are taxonomy information in all columns except column one

library("argparse") #install.packages("argparse")

parser <- ArgumentParser(description="Process classification TSV file to get taxonomy for genus interested")
parser$add_argument('-g',"--genus",help="genus for which which you'd like to know unique and counts species",required=TRUE) #interested genus
parser$add_argument('-f',"--file",help="TSV file that is to be read",required=TRUE) #TSV file that is to be read 
parser$add_argument('-o',"--odir",help="Store output directory",required=TRUE) #store output directry
parser$add_argument('-c',"--conf",help="Store output directory",required=TRUE) #store confdn
args <- parser$parse_args() #make it a data structure

genus<-args$genus #convert to lower case

if(!grepl("^[[:upper:]]", genus)){

#check if genus name starts with upper case.

cat("Genus name must start with upper case to have it prcoessed. Exiting!\n")
stop()
}

taxonomy_file<-normalizePath(args$file) #make into full path and store it
output_dir<-normalizePath(args$odir) #make into full path and store it
confdnc<-args$conf #--store confidence . wil be used in output file names
genus <- paste("^",genus,sep="")

table<-read.table(file = taxonomy_file, sep = '\t',fill = TRUE) #read file and make table

#fill = TRUE for empty value in first 7 rows

new_vector<-vector(mode = "character",length = 0) #create null vector of charater type

#this will hold all column name sthat contain genus name

  
value<-names(which(apply(table, 2, function(x) any(grepl(genus, x)
  				     		    )
  			  )
  		    )
  	      )
#grepl gives you indices. 
#2 means each column.
new_vector<-c(new_vector,value)

names_classes<-replicate(length(new_vector)+1,"character") #create column class for length col names
col_names<-c("V1",new_vector)
#create vector for col_names

data_frame<-read.table(text = "",colClasses=names_classes, col.names = col_names  )
#create data frame 

data_frame<-table[,col_names] #assign
output_file<-paste(output_dir,"/","extracted_",args$genus,"_",confdnc,".tsv",sep="") #make name for output file

write.table(data_frame,output_file,sep="\t",row.names = FALSE,col.names = FALSE,quote = FALSE)
cat("Check file ",output_file,"\n")
#----ends-