
#Date April 2017 21
#Read tab delimited file generated by python script on 16s RDP classification
#
# Along with sample name pull columns which have genus of our interest
#
#First column has sample names
#First seven rows are taxonomy information in all columns except column one

genus<-c("Prevotella","Porphyromonas") #store which genera is of interest in a vector

table<-read.table(file = 'small_tab.txt', sep = '\t') #read file

new_vector<-vector(mode = "character",length = 0) #create null vector of charater type
#this will hold all column name sthat contain genus name

for (i in 1:length(genus)){
  #loop until genus in your list
  
  value<-names(which(apply(table, 2, function(x) any(grepl(genus[i], x)))))
  #grepl gives you indices. 
  #2 means each column. 
  new_vector<-c(new_vector,value)
}


names_classes<-replicate(length(new_vector)+1,"character") #create column class for length col names
col_names<-c("V1",new_vector)
#create vector for col_names

data_frame<-read.table(text = "",colClasses=names_classes, col.names = col_names  )
#create data frame 

data_frame<-table[,col_names] #assign

write.table(data_frame,"filename.txt",sep="\t",row.names = FALSE,col.names = FALSE,quote = FALSE)

